### PR TITLE
Option to move the buttons around

### PR DESCRIPTION
**Pull request by phcs971**
Create option to move the buttons and set different location for them.

https://github.com/rebelappstudio/accessibility_tools/assets/48731731/c42bb5c1-b63d-407d-91fe-026a23b30e0c

### CODE REVIEW

**Comment by phcs971** [comment]
@aednlaxer can we run the CI again, failed due to codecov rate limit

**Comment by aednlaxer** [comment]
Thanks for another great pull request! I'll review it this week

CI jobs have been restarted

**Review by aednlaxer — APPROVED** [review]
Looks good!

**Comment by aednlaxer** [comment]
Thanks for another great contribution! These changes have been published and now available on [pub.dev](https://pub.dev/packages/accessibility_tools/versions/2.2.0)

**Pull request merged**
